
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 14 13:42:47 EST 2025
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int READ = 12;
  public static final int SEMICOLON = 9;
  public static final int ELSE = 14;
  public static final int RPAREN = 7;
  public static final int END = 17;
  public static final int RETURN = 15;
  public static final int IDENTIFIER = 3;
  public static final int IF = 13;
  public static final int QUOTEDSTRING = 4;
  public static final int LPAREN = 6;
  public static final int WRITE = 11;
  public static final int OPERATOR = 5;
  public static final int BEGIN = 16;
  public static final int TYPE = 19;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int MAIN = 18;
  public static final int error = 1;
  public static final int EQ = 10;
}

