
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 17 12:52:12 EDT 2025
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A5Sym {
  /* terminals */
  public static final int TIMES = 9;
  public static final int READ = 19;
  public static final int NE = 17;
  public static final int ELSE = 21;
  public static final int SEMICOLON = 14;
  public static final int PLUS = 7;
  public static final int RPAREN = 12;
  public static final int EQUAL = 15;
  public static final int END = 24;
  public static final int RETURN = 22;
  public static final int IDENTIFIER = 2;
  public static final int TRUE = 4;
  public static final int IF = 20;
  public static final int QUOTEDSTRING = 3;
  public static final int LPAREN = 11;
  public static final int WRITE = 18;
  public static final int BEGIN = 23;
  public static final int STRING = 26;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int NUMBER = 6;
  public static final int DIVIDE = 10;
  public static final int MAIN = 25;
  public static final int INT_T = 27;
  public static final int FALSE = 5;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int REAL_T = 28;
  public static final int EQ = 16;
}

